let process = {
    version: 'v16.14.2',
    versions: {
      node: '16.14.2',
      v8: '9.4.146.24-node.20',
      uv: '1.43.0',
      zlib: '1.2.11',
      brotli: '1.0.9',
      ares: '1.18.1',
      modules: '93',
      nghttp2: '1.45.1',
      napi: '8',
      llhttp: '6.0.4',
      openssl: '1.1.1n+quic',
      cldr: '40.0',
      icu: '70.1',
      tz: '2021a3',
      unicode: '14.0',
      ngtcp2: '0.1.0-DEV',
      nghttp3: '0.1.0-DEV'
    },
    arch: 'x64',
    platform: 'win32',
    release: {
      name: 'node',
      lts: 'Gallium',
      sourceUrl: 'https://nodejs.org/download/release/v16.14.2/node-v16.14.2.tar.gz',
      headersUrl: 'https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz',
      libUrl: 'https://nodejs.org/download/release/v16.14.2/win-x64/node.lib'
    },
    _rawDebug: [Function: _rawDebug],
    moduleLoadList: [
      'Internal Binding native_module',
      'Internal Binding errors',
      'NativeModule internal/errors',
      'Internal Binding config',
      'Internal Binding timers',
      'Internal Binding async_wrap',
      'Internal Binding constants',
      'Internal Binding util',
      'Internal Binding types',
      'NativeModule internal/util',
      'NativeModule internal/util/types',
      'NativeModule internal/validators',
      'NativeModule internal/promise_hooks',
      'Internal Binding task_queue',
      'Internal Binding symbols',
      'NativeModule internal/async_hooks',
      'NativeModule internal/linkedlist',
      'NativeModule internal/priority_queue',
      'NativeModule internal/assert',
      'Internal Binding icu',
      'NativeModule internal/util/inspect',
      'NativeModule internal/util/debuglog',
      'NativeModule internal/timers',
      'NativeModule events',
      'Internal Binding buffer',
      'Internal Binding string_decoder',
      'NativeModule internal/buffer',
      'Internal Binding blob',
      'NativeModule internal/encoding',
      'Internal Binding messaging',
      'NativeModule internal/worker/js_transferable',
      'NativeModule internal/constants',
      'NativeModule internal/blob',
      'NativeModule buffer',
      'NativeModule internal/modules/esm/handle_process_exit',
      'Internal Binding process_methods',
      'NativeModule internal/process/per_thread',
      'Internal Binding credentials',
      'NativeModule internal/process/promises',
      'NativeModule internal/fixed_queue',
      'NativeModule async_hooks',
      'NativeModule internal/process/task_queues',
      'Internal Binding trace_events',
      'NativeModule internal/console/constructor',
      'NativeModule internal/console/global',
      'NativeModule internal/util/inspector',
      'Internal Binding inspector',
      'NativeModule internal/querystring',
      'NativeModule path',
      'NativeModule querystring',
      'Internal Binding url',
      'NativeModule internal/url',
      'NativeModule util',
      'Internal Binding performance',
      'NativeModule internal/perf/utils',
      'NativeModule internal/event_target',
      'NativeModule timers',
      'NativeModule internal/abort_controller',
      'Internal Binding worker',
      'NativeModule internal/streams/operators',
      'NativeModule internal/streams/end-of-stream',
      'NativeModule internal/streams/destroy',
      'NativeModule internal/streams/legacy',
      'NativeModule internal/streams/add-abort-signal',
      'NativeModule internal/streams/buffer_list',
      'NativeModule internal/streams/state',
      'NativeModule string_decoder',
      'NativeModule internal/streams/from',
      'NativeModule internal/streams/readable',
      'NativeModule internal/streams/writable',
      'NativeModule internal/streams/duplex',
      'NativeModule internal/streams/utils',
      'NativeModule internal/streams/pipeline',
      'NativeModule internal/streams/compose',
      'NativeModule stream/promises',
      'NativeModule internal/streams/transform',
      'NativeModule internal/streams/passthrough',
      'NativeModule stream',
      'NativeModule internal/worker/io',
      'NativeModule internal/perf/performance_entry',
      'NativeModule internal/perf/observe',
      'NativeModule internal/perf/nodetiming',
      'NativeModule internal/perf/usertiming',
      'NativeModule internal/perf/event_loop_utilization',
      'NativeModule internal/histogram',
      'NativeModule internal/perf/timerify',
      'NativeModule internal/perf/performance',
      'NativeModule internal/perf/event_loop_delay',
      'NativeModule perf_hooks',
      'NativeModule internal/process/execution',
      'NativeModule internal/process/warning',
      'Internal Binding fs',
      'NativeModule internal/fs/utils',
      'Internal Binding fs_dir',
      'NativeModule internal/fs/dir',
      'Internal Binding fs_event_wrap',
      'Internal Binding uv',
      'NativeModule internal/fs/watchers',
      'NativeModule internal/fs/read_file_context',
      'NativeModule fs',
      ... 68 more items
    ],
    binding: [Function: binding],
    _linkedBinding: [Function: _linkedBinding],
    _events: [Object: null prototype] {
      newListener: [ [Function: startListeningIfSignal], [Function (anonymous)] ],
      removeListener: [ [Function: stopListeningIfSignal], [Function (anonymous)] ],
      warning: [Function: onWarning],
      SIGWINCH: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    domain: [Getter/Setter],
    _exiting: false,
    config: [Getter/Setter],
    dlopen: [Function: dlopen],
    uptime: [Function: uptime],
    _getActiveRequests: [Function: _getActiveRequests],
    _getActiveHandles: [Function: _getActiveHandles],
    getActiveResourcesInfo: [Function (anonymous)],
    reallyExit: [Function: reallyExit],
    _kill: [Function: _kill],
    cpuUsage: [Function: cpuUsage],
    resourceUsage: [Function: resourceUsage],
    memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
    kill: [Function: kill],
    exit: [Function: exit],
    hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
    openStdin: [Function (anonymous)],
    allowedNodeEnvironmentFlags: [Getter/Setter],
    assert: [Function: deprecated],
    features: {
      inspector: true,
      debug: false,
      uv: true,
      ipv6: true,
      tls_alpn: true,
      tls_sni: true,
      tls_ocsp: true,
      tls: true,
      cached_builtins: [Getter]
    },
    _fatalException: [Function (anonymous)],
    setUncaughtExceptionCaptureCallback: [Function (anonymous)],
    hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
    emitWarning: [Function: emitWarning],
    nextTick: [Function: nextTick],
    _tickCallback: [Function: runNextTicks],
    _debugProcess: [Function: _debugProcess],
    _debugEnd: [Function: _debugEnd],
    _startProfilerIdleNotifier: [Function (anonymous)],
    _stopProfilerIdleNotifier: [Function (anonymous)],
    stdout: [Getter],
    stdin: [Getter],
    stderr: [Getter],
    abort: [Function: abort],
    umask: [Function: wrappedUmask],
    chdir: [Function (anonymous)],
    cwd: [Function: wrappedCwd],
    env: {
      ACLOCAL_PATH: '/mingw64/share/aclocal:/usr/share/aclocal',
      ALLUSERSPROFILE: 'C:\\ProgramData',
      APPDATA: 'C:\\Users\\Ian\\AppData\\Roaming',
      APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
      ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
      ChocolateyLastPathUpdate: '132635181602625940',
      CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_21728_ZDKMGTQLWXRECWLR',
      COLORTERM: 'truecolor',
      COMMONPROGRAMFILES: 'C:\\Program Files\\Common Files',
      'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
      CommonProgramW6432: 'C:\\Program Files\\Common Files',
      COMPUTERNAME: 'DESKTOP-R9EFO7J',
      COMSPEC: 'C:\\WINDOWS\\system32\\cmd.exe',
      CONFIG_SITE: '/etc/config.site',
      DISPLAY: 'needs-to-be-defined',
      DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
      EXEPATH: 'C:\\Program Files\\Git\\bin',
      FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
      FPS_BROWSER_USER_PROFILE_STRING: 'Default',
      GIT_ASKPASS: 'c:\\Users\\Ian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
      HOME: 'C:\\Users\\Ian',
      HOMEDRIVE: 'C:',
      HOMEPATH: '\\Users\\Ian',
      HOSTNAME: 'DESKTOP-R9EFO7J',
      INFOPATH: '/usr/local/info:/usr/share/info:/usr/info:/share/info',
      LANG: 'en_US.UTF-8',
      LC_CTYPE: 'en_US.UTF-8',
      LOCALAPPDATA: 'C:\\Users\\Ian\\AppData\\Local',
      LOGONSERVER: '\\\\DESKTOP-R9EFO7J',
      MANPATH: '/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man',
      MINGW_CHOST: 'x86_64-w64-mingw32',
      MINGW_PACKAGE_PREFIX: 'mingw-w64-x86_64',
      MINGW_PREFIX: '/mingw64',
      MSYSTEM: 'MINGW64',
      MSYSTEM_CARCH: 'x86_64',
      MSYSTEM_CHOST: 'x86_64-w64-mingw32',
      MSYSTEM_PREFIX: '/mingw64',
      NUMBER_OF_PROCESSORS: '16',
      OLDPWD: '/c/Users/Ian/OneDrive/Desktop/devmountain/webdev-spec/week4/web-node-drills-1',
      OneDrive: 'C:\\Users\\Ian\\OneDrive',
      OneDriveConsumer: 'C:\\Users\\Ian\\OneDrive',
      ORIGINAL_PATH: 'C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\Ian\\bin;C:\\Python39\\Scripts;C:\\Python39;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Users\\Ian\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Ian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Ian\\AppData\\Roaming\\npm;C:\\Program Files\\heroku\\bin',
      ORIGINAL_TEMP: 'C:/Users/Ian/AppData/Local/Temp',
      ORIGINAL_TMP: 'C:/Users/Ian/AppData/Local/Temp',
      ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
      OS: 'Windows_NT',
      PATH: 'C:\\Users\\Ian\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\Ian\\bin;C:\\Python39\\Scripts;C:\\Python39;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\ProgramData\\h 
  ocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs;C:\\Users\\Ian\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Ian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Ian\\AppData\\Roaming\\npm;C:\\Program Files\\heroku\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl',
      PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
      PKG_CONFIG_PATH: '/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig',
      PLINK_PROTOCOL: 'ssh',
      PROCESSOR_ARCHITECTURE: 'AMD64',
      PROCESSOR_IDENTIFIER: 'AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD',
      PROCESSOR_LEVEL: '23',
      PROCESSOR_REVISION: '0802',
      ProgramData: 'C:\\ProgramData',
      PROGRAMFILES: 'C:\\Program Files',
      'ProgramFiles(x86)': 'C:\\Program Files (x86)',
      ProgramW6432: 'C:\\Program Files',
      PS1: '\\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ',
      PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
      PUBLIC: 'C:\\Users\\Public',
      PWD: '/c/Users/Ian/OneDrive/Desktop/devmountain/webdev-spec/week4/web-node-drills-1/app-2',
      SESSIONNAME: 'Console',
      SHELL: 'C:\\Program Files\\Git\\usr\\bin\\bash.exe',
      SHLVL: '3',
      SSH_ASKPASS: 'C:/Program Files/Git/mingw64/bin/git-askpass.exe',
      SYSTEMDRIVE: 'C:',
      SYSTEMROOT: 'C:\\WINDOWS',
      TEMP: 'C:\\Users\\Ian\\AppData\\Local\\Temp',
      TERM_PROGRAM: 'vscode',
      TERM_PROGRAM_VERSION: '1.67.2',
      TMP: 'C:\\Users\\Ian\\AppData\\Local\\Temp',
      TMPDIR: 'C:\\Users\\Ian\\AppData\\Local\\Temp',
      USERDOMAIN: 'DESKTOP-R9EFO7J',
      USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-R9EFO7J',
      USERNAME: 'Ian',
      USERPROFILE: 'C:\\Users\\Ian',
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
      VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\Ian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
      VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\Ian\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
      VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-8297ccc11a-sock',
      WINDIR: 'C:\\WINDOWS',
      _: '/usr/bin/winpty'
    },
    title: ' ',
    argv: [ 'C:\\Program Files\\nodejs\\node.exe' ],
    execArgv: [],
    pid: 16532,
    ppid: 9856,
    execPath: 'C:\\Program Files\\nodejs\\node.exe',
    debugPort: 9229,
    argv0: 'C:/Program Files/nodejs/node.exe',
    _preload_modules: [],
    setSourceMapsEnabled: [Function: setSourceMapsEnabled],
    [Symbol(kCapture)]: false
  }